-- ALTER Categories
ALTER TABLE categories 
ADD COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE categories 
ADD COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP;

-- ALTER SubCategories
ALTER TABLE subcategories 
ADD COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE subcategories 
ADD COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP;

-- ALTER User Categories
ALTER TABLE user_categories 
ADD COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE user_categories 
ADD COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP;

-- ALTER User SubCategories
ALTER TABLE user_subcategories
ADD COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE user_subcategories 
ADD COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP;